# -*- coding: utf-8 -*-
"""sentiment analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v71TkeXPzga5Gkg07Qkl21KbWpcCbo-y
"""

!pip tensorflow transformers

!pip install pandas scikit-learn

import pandas as pd
import regex as re
from sklearn.model_selection import train_test_split
from transformers import BertTokenizer, TFBertForSequenceClassification
import tensorflow as tf

data = pd.read_csv('/content/IMDB Dataset.csv', engine='python', on_bad_lines='warn')

def clean_text(text):
    text = re.sub(r'<.*?>', '', text)  # remove HTML tags like <br />
    text = text.strip()                # remove leading/trailing spaces
    return text

data['review'] = data['review'].apply(clean_text)


print(data.head())

print(data.shape)

print(data['review'][0])

"""avarage-len-of-reviews(in-words)"""

avg_words = data['review'].apply(lambda x: len(str(x).split())).mean()
print(avg_words)

data['sentiment'] = data['sentiment'].map({'positive': 1, 'negative': 0})

X = data['review'].values
y = data['sentiment'].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(X_train)

print(y_train)

# Load BERT tokenizer and model
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = TFBertForSequenceClassification.from_pretrained('bert-base-uncased', num_labels=2, use_safetensors=False)
# Tokenize the training data
train_encodings = tokenizer(list(X_train), truncation=True, padding=True, max_length=256, return_tensors='tf')
test_encodings = tokenizer(list(X_test), truncation=True, padding=True, max_length=256, return_tensors='tf')
# Create TensorFlow datasets
train_dataset = tf.data.Dataset.from_tensor_slices((dict(train_encodings), y_train)).shuffle(1000).batch(8)
test_dataset = tf.data.Dataset.from_tensor_slices((dict(test_encodings), y_test)).batch(8)
# Compile and train the model
model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=5e-5),
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])
# Train the model
model.fit(train_dataset, epochs=3, validation_data=test_dataset)

# After training:
model.save_pretrained("my_finetuned_model")
tokenizer.save_pretrained("my_finetuned_model")

!zip -r my_finetuned_model.zip my_finetuned_model

#  Example review text
text = "This movie was absolutely amazing! The actors did a great job."

#  Tokenize the input
inputs = tokenizer(text, return_tensors='tf', truncation=True, padding=True, max_length=256)

#  Get model predictions
outputs = model(**inputs)

#  Convert logits → probabilities → predicted label
probs = tf.nn.softmax(outputs.logits, axis=1)
pred_class = tf.argmax(probs, axis=1).numpy()[0]
if pred_class == 1:
    pred_class = "positive"
else:
    pred_class = "negative"

#  Print result
print("Probabilities:", probs.numpy())
print("Predicted class:", pred_class)